In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset.shape

(399, 25)

In [5]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [10]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [11]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset['classification_yes']

In [12]:
indep.shape

(399, 27)

In [13]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int32

In [14]:
# split into training set and test
# in regression we skip this step in gridsearch method, but in classification we do this in order to get the confusion matrix and classification report.

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [16]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid = {'criterion':['gini', 'entropy', 'log_loss'],
              'max_features':['sqrt', 'log2', None],
              'n_estimators':[10, 100, 500]}

grid = GridSearchCV(RandomForestClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')

# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [10, 100, 500]},
             scoring='f1_weighted', verbose=3)

In [17]:
# print best parameter after tuning
# print(grid.best_params_)
clf=grid.cv_results_
grid_predictions=grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, grid_predictions)

# print classification report
from sklearn.metrics import classification_report
clf_report=classification_report(y_test, grid_predictions)

In [18]:
# sample to check f1 macro value
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}: 0.9924946382275899

In [29]:
print("RF_Confusion Matrix:\n",cm)

RF_Confusion Matrix:
 [[51  0]
 [ 1 81]]

In [30]:
print("RF_Classification_Report:\n",clf_report)

RF_Classification_Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [21]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9997608799617408

In [22]:
table=pd.DataFrame.from_dict(clf)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.019889,0.000994,0.003944,0.001168,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.963284,0.981014,0.944023,0.981031,0.981031,0.970076,0.014728,15
1,0.169685,0.002870,0.008264,0.000226,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.981569,0.981014,0.981217,0.962264,1.000000,0.981213,0.011935,3
2,0.842704,0.012671,0.030727,0.001139,gini,sqrt,500,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.942166,0.981217,0.981031,0.981031,0.977089,0.018935,10
3,0.019157,0.000954,0.003075,0.000886,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.963284,0.961755,0.962573,0.962264,1.000000,0.969975,0.015021,16
4,0.167545,0.002948,0.007764,0.000959,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.981014,0.981217,0.981031,0.981031,0.984859,0.007571,1
5,0.900503,0.006670,0.031656,0.000709,gini,log2,500,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.961755,0.981217,0.981031,1.000000,0.984801,0.014284,2
6,0.023936,0.001348,0.003990,0.000248,gini,None,10,"{'criterion': 'gini', 'max_features': None, 'n...",0.926567,0.942166,0.907035,0.922492,0.981031,0.935858,0.025204,26
7,0.220601,0.002733,0.008321,0.001291,gini,None,100,"{'criterion': 'gini', 'max_features': None, 'n...",0.962963,0.942166,0.925524,0.922492,0.981031,0.946835,0.022352,23
8,1.083069,0.014824,0.029337,0.000864,gini,None,500,"{'criterion': 'gini', 'max_features': None, 'n...",0.944707,0.942166,0.925524,0.922492,0.981031,0.943184,0.020860,25
9,0.019457,0.000759,0.003919,0.000205,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.981014,0.962573,0.961826,0.961826,0.973448,0.015170,12
10,0.187085,0.004575,0.008533,0.000605,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.942166,0.962573,0.981031,0.981031,0.973360,0.019580,14
11,0.927773,0.006725,0.031953,0.001402,entropy,sqrt,500,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.942166,0.981217,0.981031,1.000000,0.980883,0.021119,5
12,0.021223,0.000812,0.003712,0.001171,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.981569,0.962264,0.907035,0.962264,1.000000,0.962627,0.031133,17
13,0.183351,0.001768,0.009552,0.000475,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.942166,0.981217,0.981031,0.981031,0.977089,0.018935,10
14,0.920342,0.004370,0.032288,0.001733,entropy,log2,500,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.942166,0.981217,0.981031,1.000000,0.980883,0.021119,5
15,0.023745,0.001207,0.003823,0.000253,entropy,None,10,"{'criterion': 'entropy', 'max_features': None,...",0.945100,0.942166,0.907035,0.922492,0.961826,0.935724,0.019020,27
16,0.222852,0.002911,0.008809,0.000923,entropy,None,100,"{'criterion': 'entropy', 'max_features': None,...",0.944707,0.942166,0.944023,0.922492,0.981031,0.946884,0.018954,22
17,1.119476,0.009022,0.030404,0.000836,entropy,None,500,"{'criterion': 'entropy', 'max_features': None,...",0.963284,0.942166,0.925524,0.922492,0.981031,0.946899,0.022398,21
18,0.020895,0.001117,0.003978,0.001245,log_loss,sqrt,10,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.981569,0.981014,0.981217,0.981031,0.961826,0.977331,0.007755,9
19,0.187184,0.001195,0.008227,0.000595,log_loss,sqrt,100,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.981569,0.942166,0.981217,0.981031,0.981031,0.973403,0.015620,13
20,0.930037,0.009226,0.030562,0.001643,log_loss,sqrt,500,"{'criterion': 'log_loss', 'max_features': 'sqr...",1.000000,0.942166,0.981217,0.981031,1.000000,0.980883,0.021119,5
21,0.020427,0.000835,0.003833,0.000589,log_loss,log2,10,"{'criterion': 'log_loss', 'max_features': 'log...",0.963284,0.943041,0.944023,0.981031,0.981217,0.962519,0.016819,18
22,0.185354,0.002853,0.008282,0.000978,log_loss,log2,100,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.961755,0.981217,0.962264,1.000000,0.981047,0.016991,4
23,0.948714,0.029389,0.031228,0.002283,log_loss,log2,500,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.942166,0.981217,0.981031,1.000000,0.980883,0.021119,5
24,0.025873,0.001456,0.003676,0.000899,log_loss,None,10,"{'criterion': 'log_loss', 'max_features': None...",0.944707,0.961755,0.907035,0.922492,0.981031,0.943404,0.026511,24
25,0.234976,0.008395,0.008293,0.000953,log_loss,None,100,"{'criterion': 'log_loss', 'max_features': None...",0.963284,0.942166,0.944023,0.922492,0.981031,0.950599,0.019957,19
26,1.243288,0.069291,0.051192,0.006327,log_loss,None,500,"{'criterion': 'log_loss', 'max_features': None...",0.963284,0.942166,0.944023,0.922492,0.981031,0.950599,0.019957,19

In [25]:
age_input=float(input("Age:"))
bp_input=float(input("bp:"))
al_input=int(input("al:"))
su_input=int(input("su:"))
bgr_input=float(input("bgr:"))
bu_input=float(input("bu:"))
sc_input=float(input("sc:"))
sod_input=float(input("sod:"))
pot_input=float(input("pot:"))
hrmo_input=float(input("hrmo:"))
pcv_input=float(input("pvc:"))
wc_input=float(input("wc:"))
rc_input=float(input("rc:"))
sg_b_input=int(input("sg_b 1 or 0:"))
sg_c_input=int(input("sg_c 1 or 0:"))
sg_d_input=int(input("sg_d 1 or 0:"))
sg_e_input=int(input("sg_e 1 or 0:"))
rbc_normal_input=int(input("rbc_normal 1 or 0:"))
pc_normal_input=int(input("pc_normal 1 or 0:"))
pcc_present_input=int(input("pcc_present 1 or 0:"))
ba_present_input=int(input("ba_present 1 or 0:"))
htn_yes_input=int(input("htn_yes 1 or 0:"))
dm_yes_input=int(input("dm_yes 1 or 0:"))
cad_yes_input=int(input("cad_yes 1 or 0:"))
appet_yes_input=int(input("appet_yes 1 or 0:"))
pe_yes_input=int(input("pe_yes 1 or 0:"))
ane_yes_input=int(input("ane_yes 1 or 0:"))

Age: 45
bp: 50
al: 1
su: 2
bgr: 3
bu: 45
sc: 15
sod: 155
pot: 600
hrmo: 700
pvc: 500
wc: 300
rc: 451
sg_b 1 or 0: 1
sg_c 1 or 0: 1
sg_d 1 or 0: 1
sg_e 1 or 0: 1
rbc_normal 1 or 0: 0
pc_normal 1 or 0: 1
pcc_present 1 or 0: 0
ba_present 1 or 0: 1
htn_yes 1 or 0: 0
dm_yes 1 or 0: 1
cad_yes 1 or 0: 0
appet_yes 1 or 0: 1
pe_yes 1 or 0: 0
ane_yes 1 or 0: 1

In [28]:
Future_Prediction = grid.predict([[age_input, bp_input, al_input, su_input, bgr_input, bu_input, 
                                   sc_input, sod_input, pot_input, hrmo_input, pcv_input, wc_input, 
                                   rc_input, sg_b_input, sg_c_input, sg_d_input, sg_e_input, rbc_normal_input, 
                                   pc_normal_input, pcc_present_input, ba_present_input, htn_yes_input, dm_yes_input, 
                                   cad_yes_input, appet_yes_input, pe_yes_input, ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]