In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset.shape

(399, 25)

In [5]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [9]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset['classification_yes']

In [10]:
indep.shape

(399, 27)

In [11]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int32

In [12]:
# split into training set and test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
param_grid = {'criterion':['gini', 'entropy', 'log_loss'],
              'splitter':['best', 'random'],
              'max_features':['sqrt', 'log2', None]}

grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')

# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2', None],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [15]:
# print best parameter after tuning
# print(grid.best_params_)
clf=grid.cv_results_
grid_predictions=grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, grid_predictions)

# print classification report
from sklearn.metrics import classification_report
clf_report=classification_report(y_test, grid_predictions)

In [16]:
# sample to check f1 macro value
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': None, 'splitter': 'random'}: 0.9625928174473452

In [23]:
print("DT_Confusion Matrix:\n",cm)

DT_Confusion Matrix:
 [[50  1]
 [ 4 78]]

In [24]:
print("DT_Classification_Report:\n",clf_report)

DT_Classification_Report:
               precision    recall  f1-score   support

           0       0.93      0.98      0.95        51
           1       0.99      0.95      0.97        82

    accuracy                           0.96       133
   macro avg       0.96      0.97      0.96       133
weighted avg       0.96      0.96      0.96       133

In [19]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9658058345289334

In [20]:
table=pd.DataFrame.from_dict(clf)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002603,6.467293e-04,0.003045,0.000898,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.963284,0.905069,0.925524,0.942332,0.981217,0.943485,0.026890,13
1,0.001868,1.902137e-03,0.001358,0.001143,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.945100,0.923510,0.981217,0.924528,0.962573,0.947386,0.022239,10
2,0.001758,1.364310e-03,0.002752,0.000753,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.963284,0.962264,0.944023,0.905155,0.943093,0.943564,0.021044,11
3,0.001645,1.004873e-03,0.002689,0.000758,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.981569,0.943041,1.000000,0.924528,0.962573,0.962342,0.026796,7
4,0.001890,1.072212e-03,0.003163,0.001254,gini,None,best,"{'criterion': 'gini', 'max_features': None, 's...",0.926567,0.961755,0.962573,0.922492,0.942332,0.943144,0.016887,14
5,0.001423,7.406503e-04,0.003095,0.000716,gini,None,random,"{'criterion': 'gini', 'max_features': None, 's...",1.000000,0.981014,1.000000,0.981217,1.000000,0.992446,0.009252,1
6,0.002009,3.177185e-04,0.002584,0.000605,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.926978,0.922185,0.944023,0.943093,0.981217,0.943499,0.020738,12
7,0.001638,1.038063e-03,0.002615,0.000494,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.963284,0.962264,0.962573,0.981031,0.981031,0.970037,0.008983,3
8,0.001610,8.050919e-04,0.002712,0.000874,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.981378,0.942166,0.925524,0.961826,0.981031,0.958385,0.021892,9
9,0.001986,5.969389e-04,0.002162,0.000768,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.981569,0.924528,0.962573,0.850292,0.961826,0.936158,0.046748,16
10,0.003455,1.979547e-03,0.003187,0.001196,entropy,None,best,"{'criterion': 'entropy', 'max_features': None,...",0.908877,0.942166,0.962573,0.922492,0.962264,0.939674,0.021376,15
11,0.001717,3.096658e-04,0.005660,0.005101,entropy,None,random,"{'criterion': 'entropy', 'max_features': None,...",0.981569,0.925272,1.000000,0.925146,0.981217,0.962641,0.031309,6
12,0.001315,1.250855e-03,0.002210,0.000402,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.944707,0.925272,0.906705,0.906085,0.943651,0.925284,0.016902,18
13,0.000727,8.986565e-04,0.003124,0.001113,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.981569,0.981014,0.981217,0.962264,1.000000,0.981213,0.011935,2
14,0.001051,8.693006e-04,0.002645,0.000821,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.962264,0.944023,0.962264,0.962264,0.966163,0.018334,5
15,0.001279,1.052991e-03,0.002083,0.000147,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",0.945100,0.962264,0.981217,0.981217,0.923652,0.958690,0.022091,8
16,0.002008,5.761645e-07,0.002227,0.000689,log_loss,None,best,"{'criterion': 'log_loss', 'max_features': None...",0.872428,0.942166,0.944023,0.922492,0.981031,0.932428,0.035469,17
17,0.001318,8.794745e-04,0.001754,0.001009,log_loss,None,random,"{'criterion': 'log_loss', 'max_features': None...",0.981569,0.944161,0.981217,0.943651,0.981217,0.966363,0.018337,4

In [21]:
age_input=float(input("Age:"))
bp_input=float(input("bp:"))
al_input=int(input("al:"))
su_input=int(input("su:"))
bgr_input=float(input("bgr:"))
bu_input=float(input("bu:"))
sc_input=float(input("sc:"))
sod_input=float(input("sod:"))
pot_input=float(input("pot:"))
hrmo_input=float(input("hrmo:"))
pcv_input=float(input("pvc:"))
wc_input=float(input("wc:"))
rc_input=float(input("rc:"))
sg_b_input=int(input("sg_b 1 or 0:"))
sg_c_input=int(input("sg_c 1 or 0:"))
sg_d_input=int(input("sg_d 1 or 0:"))
sg_e_input=int(input("sg_e 1 or 0:"))
rbc_normal_input=int(input("rbc_normal 1 or 0:"))
pc_normal_input=int(input("pc_normal 1 or 0:"))
pcc_present_input=int(input("pcc_present 1 or 0:"))
ba_present_input=int(input("ba_present 1 or 0:"))
htn_yes_input=int(input("htn_yes 1 or 0:"))
dm_yes_input=int(input("dm_yes 1 or 0:"))
cad_yes_input=int(input("cad_yes 1 or 0:"))
appet_yes_input=int(input("appet_yes 1 or 0:"))
pe_yes_input=int(input("pe_yes 1 or 0:"))
ane_yes_input=int(input("ane_yes 1 or 0:"))

Age: 58
bp: 650
al: 230
su: 245
bgr: 1
bu: 12
sc: 132
sod: 458
pot: 97.5
hrmo: 987.2
pvc: 25
wc: 33
rc: 14
sg_b 1 or 0: 0
sg_c 1 or 0: 1
sg_d 1 or 0: 0
sg_e 1 or 0: 1
rbc_normal 1 or 0: 0
pc_normal 1 or 0: 1
pcc_present 1 or 0: 01
ba_present 1 or 0: 0
htn_yes 1 or 0: 1
dm_yes 1 or 0: 0
cad_yes 1 or 0: 1
appet_yes 1 or 0: 1
pe_yes 1 or 0: 1
ane_yes 1 or 0: 1

In [22]:
Future_Prediction = grid.predict([[age_input, bp_input, al_input, su_input, bgr_input, bu_input, 
                                   sc_input, sod_input, pot_input, hrmo_input, pcv_input, wc_input, 
                                   rc_input, sg_b_input, sg_c_input, sg_d_input, sg_e_input, rbc_normal_input, 
                                   pc_normal_input, pcc_present_input, ba_present_input, htn_yes_input, dm_yes_input, 
                                   cad_yes_input, appet_yes_input, pe_yes_input, ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]