In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset.shape

(399, 25)

In [5]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [9]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset['classification_yes']

In [10]:
indep.shape

(399, 27)

In [11]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int32

In [12]:
# split into training set and test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
param_grid = {'n_neighbors':[3,5,7,10,20],
              'weights':['uniform', 'distance'],
              'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],
              'metric':['minkowski'], 'p':[2,3,4,5]}

grid = GridSearchCV(KNeighborsClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')

# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 160 candidates, totalling 800 fits

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['minkowski'],
                         'n_neighbors': [3, 5, 7, 10, 20], 'p': [2, 3, 4, 5],
                         'weights': ['uniform', 'distance']},
             scoring='f1_weighted', verbose=3)

In [15]:
# print best parameter after tuning
# print(grid.best_params_)
clf=grid.cv_results_
grid_predictions=grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, grid_predictions)

# print classification report
from sklearn.metrics import classification_report
clf_report=classification_report(y_test, grid_predictions)

C:\Users\Default.DESKTOP-73FCCDO\Documents\Installations\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\Default.DESKTOP-73FCCDO\Documents\Installations\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Users\Default.DESKTOP-73FCCDO\Documents\Installations\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Default.DESKTOP-73FCCDO\Documents\Installations\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Default.DESKTOP-73FCCDO\Documents\Installations\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In [16]:
# sample to check f1 macro value
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'algorithm': 'auto', 'metric': 'minkowski', 'n_neighbors': 3, 'p': 2, 'weights': 'uniform'}: 0.9626932787797391

In [17]:
print("KNN_Confusion Matrix:\n",cm)

KNN_Confusion Matrix:
 [[51  0]
 [ 5 77]]

In [18]:
print("KNN_Classification_Report:\n",clf_report)

KNN_Classification_Report:
               precision    recall  f1-score   support

           0       0.91      1.00      0.95        51
           1       1.00      0.94      0.97        82

    accuracy                           0.96       133
   macro avg       0.96      0.97      0.96       133
weighted avg       0.97      0.96      0.96       133

In [19]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.998804399808704

In [20]:
table=pd.DataFrame.from_dict(clf)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002470,0.001070,0.109677,0.006732,auto,minkowski,3,2,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.981569,0.981233,0.944023,0.962573,1.000000,0.973880,0.019051,1
1,0.002569,0.000513,0.064342,0.051185,auto,minkowski,3,2,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.981569,0.981233,0.944023,0.962573,1.000000,0.973880,0.019051,1
2,0.001002,0.000911,0.009204,0.000985,auto,minkowski,3,3,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.981569,0.962264,0.962573,0.962573,1.000000,0.973796,0.015046,25
3,0.001008,0.000902,0.009078,0.000734,auto,minkowski,3,3,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.981569,0.962264,0.962573,0.962573,1.000000,0.973796,0.015046,25
4,0.000835,0.000761,0.008701,0.001076,auto,minkowski,3,4,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.981569,0.943699,0.962573,0.981217,1.000000,0.973812,0.019151,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,0.002917,0.001817,0.024088,0.002554,brute,minkowski,20,3,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.835928,0.907402,0.869925,0.944023,0.962573,0.903970,0.046560,133
156,0.003918,0.003032,0.019373,0.004943,brute,minkowski,20,4,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.798609,0.907402,0.851225,0.907035,0.944023,0.881659,0.051028,153
157,0.002523,0.001103,0.025322,0.001481,brute,minkowski,20,4,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.835928,0.907402,0.869925,0.925524,0.962573,0.900270,0.043889,137
158,0.002567,0.000759,0.024352,0.000468,brute,minkowski,20,5,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.798609,0.889033,0.851225,0.925524,0.944023,0.881683,0.052329,149
159,0.003323,0.001096,0.025589,0.003213,brute,minkowski,20,5,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.798609,0.925764,0.869925,0.925524,0.962573,0.896479,0.057190,141

In [21]:
age_input=float(input("Age:"))
bp_input=float(input("bp:"))
al_input=int(input("al:"))
su_input=int(input("su:"))
bgr_input=float(input("bgr:"))
bu_input=float(input("bu:"))
sc_input=float(input("sc:"))
sod_input=float(input("sod:"))
pot_input=float(input("pot:"))
hrmo_input=float(input("hrmo:"))
pcv_input=float(input("pvc:"))
wc_input=float(input("wc:"))
rc_input=float(input("rc:"))
sg_b_input=int(input("sg_b 1 or 0:"))
sg_c_input=int(input("sg_c 1 or 0:"))
sg_d_input=int(input("sg_d 1 or 0:"))
sg_e_input=int(input("sg_e 1 or 0:"))
rbc_normal_input=int(input("rbc_normal 1 or 0:"))
pc_normal_input=int(input("pc_normal 1 or 0:"))
pcc_present_input=int(input("pcc_present 1 or 0:"))
ba_present_input=int(input("ba_present 1 or 0:"))
htn_yes_input=int(input("htn_yes 1 or 0:"))
dm_yes_input=int(input("dm_yes 1 or 0:"))
cad_yes_input=int(input("cad_yes 1 or 0:"))
appet_yes_input=int(input("appet_yes 1 or 0:"))
pe_yes_input=int(input("pe_yes 1 or 0:"))
ane_yes_input=int(input("ane_yes 1 or 0:"))

Age: 44
bp: 66
al: 33
su: 22
bgr: 15
bu: 44
sc: 77
sod: 88
pot: 99
hrmo: 25
pvc: 36
wc: 99
rc: 66
sg_b 1 or 0: 1
sg_c 1 or 0: 1
sg_d 1 or 0: 1
sg_e 1 or 0: 1
rbc_normal 1 or 0: 1
pc_normal 1 or 0: 1
pcc_present 1 or 0: 1
ba_present 1 or 0: 1
htn_yes 1 or 0: 1
dm_yes 1 or 0: 1
cad_yes 1 or 0: 1
appet_yes 1 or 0: 1
pe_yes 1 or 0: 1
ane_yes 1 or 0: 1

In [22]:
Future_Prediction = grid.predict([[age_input, bp_input, al_input, su_input, bgr_input, bu_input, 
                                   sc_input, sod_input, pot_input, hrmo_input, pcv_input, wc_input, 
                                   rc_input, sg_b_input, sg_c_input, sg_d_input, sg_e_input, rbc_normal_input, 
                                   pc_normal_input, pcc_present_input, ba_present_input, htn_yes_input, dm_yes_input, 
                                   cad_yes_input, appet_yes_input, pe_yes_input, ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]