In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset.shape

(399, 25)

In [5]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [9]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset['classification_yes']

In [10]:
indep.shape

(399, 27)

In [11]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int32

In [12]:
# split into training set and test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [ ]:
# We didn't standardize the data because, MultinomialNB only works with non-negative features (counts / frequencies).
# If we use StandardScaler, we will create negatives.

In [13]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB
param_grid = param_grid = {'alpha': [0.01, 0.1, 0.5, 1.0, 5.0, 10.0], 'fit_prior': [True, False]}

grid = GridSearchCV(MultinomialNB(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')

# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=MultinomialNB(), n_jobs=-1,
             param_grid={'alpha': [0.01, 0.1, 0.5, 1.0, 5.0, 10.0],
                         'fit_prior': [True, False]},
             scoring='f1_weighted', verbose=3)

In [14]:
# print best parameter after tuning
# print(grid.best_params_)
clf=grid.cv_results_
grid_predictions=grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, grid_predictions)

# print classification report
from sklearn.metrics import classification_report
clf_report=classification_report(y_test, grid_predictions)

In [15]:
# sample to check f1 macro value
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'alpha': 0.01, 'fit_prior': True}: 0.888737824982843

In [16]:
print("MultinomialNB_Confusion Matrix:\n",cm)

MultinomialNB_Confusion Matrix:
 [[50  1]
 [14 68]]

In [17]:
print("MultinomialNB_Classification_Report:\n",clf_report)

MultinomialNB_Classification_Report:
               precision    recall  f1-score   support

           0       0.78      0.98      0.87        51
           1       0.99      0.83      0.90        82

    accuracy                           0.89       133
   macro avg       0.88      0.90      0.89       133
weighted avg       0.91      0.89      0.89       133

In [18]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.947871831659493

In [19]:
table=pd.DataFrame.from_dict(clf)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_fit_prior,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.065495,0.022457,0.005066,0.000000,0.01,True,"{'alpha': 0.01, 'fit_prior': True}",0.872586,0.906166,0.925524,0.907035,0.925146,0.907291,0.019272,1
1,0.021663,0.020149,0.004731,0.001791,0.01,False,"{'alpha': 0.01, 'fit_prior': False}",0.872586,0.906166,0.907035,0.907035,0.925146,0.903594,0.017066,2
2,0.004364,0.000203,0.003260,0.000387,0.10,True,"{'alpha': 0.1, 'fit_prior': True}",0.835928,0.869709,0.888515,0.888515,0.888286,0.874191,0.020461,3
3,0.003567,0.000509,0.003806,0.000241,0.10,False,"{'alpha': 0.1, 'fit_prior': False}",0.835928,0.851527,0.888515,0.888515,0.888286,0.870554,0.022453,4
4,0.004001,0.000547,0.002902,0.000487,0.50,True,"{'alpha': 0.5, 'fit_prior': True}",0.817369,0.851527,0.869925,0.888515,0.869849,0.859437,0.024067,5
5,0.002350,0.001336,0.001643,0.002445,0.50,False,"{'alpha': 0.5, 'fit_prior': False}",0.817369,0.851527,0.869925,0.888515,0.869849,0.859437,0.024067,5
6,0.005458,0.003175,0.003617,0.001887,1.00,True,"{'alpha': 1.0, 'fit_prior': True}",0.817369,0.851527,0.869925,0.888515,0.851354,0.855738,0.023600,7
7,0.004089,0.001556,0.002849,0.001187,1.00,False,"{'alpha': 1.0, 'fit_prior': False}",0.817369,0.851527,0.869925,0.869925,0.851354,0.852020,0.019197,8
8,0.002952,0.000897,0.003429,0.000775,5.00,True,"{'alpha': 5.0, 'fit_prior': True}",0.798609,0.796687,0.851225,0.851225,0.851354,0.829820,0.026276,9
9,0.003870,0.000701,0.003663,0.000602,5.00,False,"{'alpha': 5.0, 'fit_prior': False}",0.798609,0.796687,0.851225,0.851225,0.851354,0.829820,0.026276,9
10,0.003747,0.000300,0.003598,0.000600,10.00,True,"{'alpha': 10.0, 'fit_prior': True}",0.798609,0.778179,0.851225,0.794081,0.851354,0.814689,0.030645,11
11,0.003307,0.000965,0.002970,0.001009,10.00,False,"{'alpha': 10.0, 'fit_prior': False}",0.779609,0.778179,0.851225,0.794081,0.851354,0.810890,0.033452,12

In [20]:
age_input=float(input("Age:"))
bp_input=float(input("bp:"))
al_input=int(input("al:"))
su_input=int(input("su:"))
bgr_input=float(input("bgr:"))
bu_input=float(input("bu:"))
sc_input=float(input("sc:"))
sod_input=float(input("sod:"))
pot_input=float(input("pot:"))
hrmo_input=float(input("hrmo:"))
pcv_input=float(input("pvc:"))
wc_input=float(input("wc:"))
rc_input=float(input("rc:"))
sg_b_input=int(input("sg_b 1 or 0:"))
sg_c_input=int(input("sg_c 1 or 0:"))
sg_d_input=int(input("sg_d 1 or 0:"))
sg_e_input=int(input("sg_e 1 or 0:"))
rbc_normal_input=int(input("rbc_normal 1 or 0:"))
pc_normal_input=int(input("pc_normal 1 or 0:"))
pcc_present_input=int(input("pcc_present 1 or 0:"))
ba_present_input=int(input("ba_present 1 or 0:"))
htn_yes_input=int(input("htn_yes 1 or 0:"))
dm_yes_input=int(input("dm_yes 1 or 0:"))
cad_yes_input=int(input("cad_yes 1 or 0:"))
appet_yes_input=int(input("appet_yes 1 or 0:"))
pe_yes_input=int(input("pe_yes 1 or 0:"))
ane_yes_input=int(input("ane_yes 1 or 0:"))

Age: 25
bp: 458
al: 84
su: 51
bgr: 12
bu: 456
sc: 123
sod: 789
pot: 258
hrmo: 369
pvc: 147
wc: 146
rc: 3.2
sg_b 1 or 0: 1
sg_c 1 or 0: 1
sg_d 1 or 0: 1
sg_e 1 or 0: 1
rbc_normal 1 or 0: 1
pc_normal 1 or 0: 1
pcc_present 1 or 0: 1
ba_present 1 or 0: 1
htn_yes 1 or 0: 1
dm_yes 1 or 0: 1
cad_yes 1 or 0: 0
appet_yes 1 or 0: 0
pe_yes 1 or 0: 0
ane_yes 1 or 0: 0

In [21]:
Future_Prediction = grid.predict([[age_input, bp_input, al_input, su_input, bgr_input, bu_input, 
                                   sc_input, sod_input, pot_input, hrmo_input, pcv_input, wc_input, 
                                   rc_input, sg_b_input, sg_c_input, sg_d_input, sg_e_input, rbc_normal_input, 
                                   pc_normal_input, pcc_present_input, ba_present_input, htn_yes_input, dm_yes_input, 
                                   cad_yes_input, appet_yes_input, pe_yes_input, ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]

C:\Users\Default.DESKTOP-73FCCDO\Documents\Installations\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(